//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Saifutdinov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Adress { get; set; }
        public string Passport { get; set; }
        public string StacTexnology { get; set; }
        public int IdRole { get; set; }
        public int IdPost { get; set; }
        public int IdOrganization { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Post Post { get; set; }
        public virtual Role Role { get; set; }
    }
}
